server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  loki:
    url: "http://172.37.66.191:3100/loki/api/v1/push"
    external_labels:
      promtail_env: "dev3"
  # kafka:
  #   url: "172.37.101.16:9092"
  # file_system_config:
  #   path: "/tmp/promtail/log"

scrape_configs:
- job_name: system
  pipeline_stages:
  - match:
      selector: '{filename=~".*/app.log"}'
      stages:
      - regex:
          expression: '(?P<timestamp>\S*\s\S*)\s{1,4}(?P<level>\S*)\s{1,3}(?P<pid>\S*)\s{1,4}\[(?P<traceId>.*?),(?P<spanId>.*?)\]\s{1,4}\[TID:\s{0,1}(?P<tId>.*?)\]\s{1,2}\[T:\s{0,2}(?P<tenantId>.*?)\]\s{1,3}---\s{1,3}\[(?P<thread>.*?)\]\s{1,3}(?P<logger>\S*)\s{1,3}\[(?P<className>.*?):(?P<line>\d{1,6})\]\s{1,3}:\s{1,3}(?P<message>.*?)$'
      - labels:
          timestamp:
          level:
          pid:
          traceId:
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /tmp/logs/*.log


# for file discovery
#- job_name: file_discovery
#  file_sd_configs:
#    - files:
#      - target.json
#      refresh_interval: 10s
