clients:
  - file_system_config:
      path: /tmp/promtail/log
#  - kafka:
#      batch_size: 400000
#      url: "172.35.88.54:9092"

positions:
  filename: /tmp/positions.yaml
server:
  http_listen_port: 43101
  grpc_listen_port: 49005
target_config:
  sync_period: 10s
scrape_configs:
  - job_name: file_discovery
    file_sd_configs:
      - files:
          - file.json
        refresh_interval: 10s