clients:
  - file_system_config:
      path: /tmp/promtail/log
  - kafka:
      batch_size: 2097152
      url: "192.168.246.85:9092"
      producer_max_message_size: 2097152

positions:
  filename: /tmp/positions.yaml
server:
  http_listen_port: 43101
  grpc_listen_port: 49005
target_config:
  sync_period: 10s
scrape_configs:
  - job_name: file_discovery
    file_sd_configs:
      - files:
          - file.json
        refresh_interval: 10s